# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
    analytics:
        gtag: G-ABC123
    prev_next_buttons_location: top
site_name: wxh-notebook

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - 主页: 'index.md'
    - 光子学:
        - 'photonics/photonics.md'
    - 机器学习:
        - 'machine_learning/machine_learning.md'